# vi: set ft=yaml.ansible :
- name: Configure Backgrounds
  vars:
    gnome_background_properties: /usr/share/gnome-background-properties
    dconf_local_d: /etc/dconf/db/local.d
    backgrounds_dir: /usr/local/share/backgrounds/
    background_conf: '{{ lookup("template", "./templates/00-backgrounds.conf.j2" ) }}'
    backgrounds_xml: '{{ lookup("template", "./templates/backgrounds.xml.j2") }}'
    screensaver_conf: '{{ lookup("template", "./templates/01-screensaver.conf.j2") }}'
  tags:
    - backgrounds
    - desktop
  block:
    - name: Add Backgrounds
      block:
        - name: Get all of the background paths
          ansible.builtin.find:
            paths: "{{ backgrounds.directory }}"
          register: backgrounds_directory_files
        - name: Copy Backgrounds into Shared System Location
          become: true
          ansible.builtin.copy:
            src: '{{ item.path }}'
            dest: "{{ backgrounds_dir }}/{{ item.path | split('/') | last }}"
            mode: '0744'
          loop: '{{ backgrounds_directory_files.files }}'
    - name: Configure Available Backgrounds
      block:
        - name: "List Available Backgrounds for GNOME Configuration"
          ansible.builtin.find:
            paths: '{{ backgrounds_dir }}'
          register: background_paths
        - name: "Generate GNOME Backgrounds Configuration"
          ansible.builtin.copy:
            content: '{{ backgrounds_xml }}'
            dest: '{{ artifacts.backgrounds }}/backgrounds.xml'
            mode: '0744'
        - name: "Save GNOME Backgrounds Configuration"
          become: true
          ansible.builtin.copy:
            content: '{{ backgrounds_xml }}'
            dest: '{{ gnome_background_properties }}/custom.xml'
            mode: '0744'
    - name: Set the default wallpaper for the desktop
      block:
        - name: "Generate `dconf` Backgrounds Configuration."
          ansible.builtin.copy:
            content: '{{ background_conf }}'
            dest: '{{ artifacts.backgrounds }}/background.conf'
            mode: '0744'
        - name: "Save `dconf` Backgrounds Configuration"
          become: true
          ansible.builtin.copy:
            content: '{{ background_conf }}'
            dest: '{{ dconf_local_d }}/00-background'
            mode: '0744'
    - name: Set the default wallpaper for the homescreen.
      block:
        - name: "Generate `dconf` Screensaver Config"
          ansible.builtin.copy:
            content: '{{ screensaver_conf }}'
            dest: '{{ artifacts.backgrounds }}/screensaver.conf'
            mode: '0744'
        - name: "Save `dconf` Screensaver Config"
          become: true
          ansible.builtin.copy:
            content: '{{ screensaver_conf }}'
            dest: '{{ dconf_local_d }}/01-screensaver'
            mode: '0744'
    - name: Restart `dconf`.
      become: true
      ansible.builtin.shell: "dconf update"
