project:
  type: website
website:
  title: "Virtualization Topics Notebooks"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: docked
    contents:
      - href: ./libvirt.qmd
        text: Libvirt
      - href: ./rhel.qmd
        text: RHEL
      - href: "./ansible.qmd"
        text: About Ansible
format:
  html:
    theme:
      - cosmo
      - brand
      - index.scss
    toc: true
