general:
  primary_user: acederberg
#
# NOTE(acederberg): See the `desktop` playbook.
#
dekstop:
  backgrounds:
    screensaver: pascal-debrunner-TOKeCFmRtj4-unsplash.jpg
    desktop: pascal-debrunner-TOKeCFmRtj4-unsplash.jpg
    directory: /home/acederberg/Pictures/Wallpapers
#
# NOTE(acederberg): See the `tools` playbook.
# 
tools:
  argocd:
    repo: argoproj/argo-cd
    version: 3.1.8
    checksum: sha256:bfc45149df6dc8408cee3c1c66e865adde1439d8f419657513b56704d73f1e4d
  helm:
    repo: helm/helm
    version: 3.19.0
    checksum: sha256:a7f81ce08007091b86d8bd696eb4d86b8d0f2e1b9f6c714be62f82f96a594496
  kubectl:
    version: 1.34.1
    checksum: sha256:7721f265e18709862655affba5343e85e1980639395d5754473dafaadcaa69e3
  terraform:
    version: 1.13.4
    checksum: sha256:98aa516201e948306698efd9954ab4cc0d1227c2578ba56245898b5f679e590b
  # go:
  #   version: 1.25.3
  #   checksum: sha256
  kitty:
    version: 0.43.1
    checksum: sha256:f2026ef8cec6fd21b58e3ae501f707c2fc922ddb9b3e79685917fc60197449fb
