# vi: set ft=yaml.ansible :
- name: Gather and print local facts
  hosts: libvirt
  gather_facts: true
  tasks:
    - name: "Print Facts"
      debug:
        msg: "Connected as {{ ansible_user_id }}@{{ ansible_hostname }}"
    - name: Get Running Virtual Machines.
      community.libvirt.virt:
        command: list_vms
      register: libvirt_vms
    - name: Print Running Virtual Machines.
      ansible.builtin.debug:
        var: libvirt_vms
